# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-13 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20171113_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='detail2',
        ),
    ]
